---
- name: Include Ubuntu specific tasks
  ansible.builtin.include_tasks: ubuntu.yaml
  when: ansible_facts['os_family'] == 'Debian'

- name: Stop and disable package redis-server service
  ansible.builtin.systemd:
    name: redis-server
    state: stopped
    enabled: false
  become: true
  ignore_errors: true

- name: Run fs operations
  ansible.builtin.include_tasks: fs.yaml

- name: Configure redis
  ansible.builtin.include_tasks: configure.yaml

- name: Enable and start redis
  ansible.builtin.systemd:
    name: redis
    enabled: true
    state: started
  become: true
