---
- name: Include Ubuntu specific tasks
  ansible.builtin.include_tasks: ubuntu.yaml
  when: OS == 'Ubuntu'

- name: Stop and disable package redis-server service
  ansible.builtin.systemd:
    name: redis-server
    state: stopped
    enabled: false
  become: true
  ignore_errors: true

- name: Run fs operations
  ansible.builtin.include_tasks: fs.yaml

- name: Configure redis
  ansible.builtin.include_tasks: configure.yaml
