---
dependencies: []

galaxy_info:
  role_name: dnsmasq
  author: 1kbgz
  description: Install and configure dnsmasq as DNS server
  license: AGPL-3.0
  min_ansible_version: "2.12"
  platforms:
    - name: Ubuntu
  galaxy_tags:
    - development
