---
- name: Run fs operations
  ansible.builtin.include_tasks: fs.yaml

- name: Configure nginx
  ansible.builtin.include_tasks: configure.yaml

- name: Configure nginx
  ansible.builtin.include_tasks: configure.yaml
