---
dependencies: []

galaxy_info:
  role_name: wireguard_server_ui
  author: 1kbgz
  description: Install and configure UI for wireguard server
  license: AGPL-3.0
  min_ansible_version: "2.12"
  platforms:
    - name: Ubuntu
  galaxy_tags:
    - development
