---
COMPUTE_BATCH_CPU_QUOTA: ''
COMPUTE_BATCH_CPU_WEIGHT: 100
COMPUTE_BATCH_IO_WEIGHT: 100
COMPUTE_BATCH_MEMORY_HIGH: infinity
COMPUTE_BATCH_MEMORY_MAX: infinity
COMPUTE_BATCH_MEMORY_SWAP_MAX: infinity
COMPUTE_BATCH_TASKS_MAX: infinity
COMPUTE_BATCH_MANAGED_OOM_MEMORY_PRESSURE: auto
COMPUTE_BATCH_MANAGED_OOM_MEMORY_PRESSURE_LIMIT: ''
COMPUTE_BATCH_MANAGED_OOM_SWAP: auto
