---
FORGEJO_RUNNER_VERSION: 13.0.0
FORGEJO_RUNNER_CHECKSUMS:
  amd64: cfcfe65e9ed5c9a4b344acfdbc3c32210b274c005a5888f46967c4d988177707
  arm64: 71118fc208efc8853d8e9f400d316bff0eb14cfafc7407ba92ca49eb0972935f
FORGEJO_RUNNER_ARCHITECTURES:
  x86_64: amd64
  aarch64: arm64
FORGEJO_RUNNER_USER: forgejo-runner
FORGEJO_RUNNER_NAME: "{{ inventory_hostname }}"
FORGEJO_RUNNER_URL: ''
FORGEJO_RUNNER_UUID: ''
FORGEJO_RUNNER_TOKEN: ''
FORGEJO_RUNNER_LABELS: []
FORGEJO_RUNNER_ENABLED: true
FORGEJO_RUNNER_CAPACITY: 1
FORGEJO_RUNNER_TIMEOUT: 1h
FORGEJO_RUNNER_SHUTDOWN_TIMEOUT: 10m
FORGEJO_RUNNER_CONTAINER_OPTIONS: >-
  --cpus=2 --memory=2g --memory-swap=3g --pids-limit=256
FORGEJO_RUNNER_MEMORY_MAX: 3G
FORGEJO_RUNNER_CPU_WEIGHT: 25
FORGEJO_RUNNER_IO_WEIGHT: 25
FORGEJO_RUNNER_OOM_SCORE_ADJUST: 500
