---
- name: Restart cron
  ansible.builtin.systemd:
    name: "{{ 'crond' if OS == 'EL' else 'cron' }}"
    state: restarted
    enabled: true

- name: Restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted
    enabled: true

- name: Restart firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: restarted
    enabled: true

- name: Restart resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted
    enabled: true

- name: Stop lighttpd
  ansible.builtin.systemd:
    name: lighttpd
    state: stopped
    enabled: false

- name: Stop dnsmasq
  ansible.builtin.systemd:
    name: dnsmasq
    state: stopped
    enabled: false
