---
- name: Restart firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: restarted
    enabled: true

- name: Restart NoMachine
  ansible.builtin.systemd:
    name: nxserver
    state: restarted
    enabled: true
