---
galaxy_info:
  author: 1kbgz
  description: Install + configure Headscale + Caddy + Tailscale on a hub
  license: MIT
  min_ansible_version: '2.14'
  platforms:
    - name: Ubuntu
      versions: [all]
