---
PYTHON_LIBRARIES_VIRTUALENV:
PYTHON_LIBRARIES_USER:
PYTHON_LIBRARIES_PACKAGES: []
PYTHON_LIBRARIES_PACKAGES_NO_DEPS: []
PYTHON_LIBRARIES_EDITABLE_PATHS: []
PYTHON_LIBRARIES_ENVIRONMENT: {}
PYTHON_LIBRARIES_IMPORTS: []
PYTHON_LIBRARIES_RESTART_SERVICES: []
PYTHON_LIBRARIES_SOURCE_CHANGED: false
