---
- name: Create openvpn-monitor working folder
  ansible.builtin.file:
    path: /var/lib/openvpn-monitor
    state: directory
    mode: '0755'
    owner: vpnmon
    group: services
  become: true

- name: Create openvpn-monitor log folder
  ansible.builtin.file:
    path: /var/log/openvpn-monitor
    state: directory
    mode: '0755'
    owner: vpnmon
    group: services
  become: true
