---
- name: Run fs operations
  ansible.builtin.include_tasks: fs.yaml

- name: Configure openvpn-monitor
  ansible.builtin.include_tasks: configure.yaml

- name: Setup Virtualenv
  ansible.builtin.include_tasks: venv.yaml
