---
- name: Copy airflow-celery-flower service
  ansible.builtin.copy:
    dest: /lib/systemd/system/airflow-celery-flower.service
    mode: '0644'
    owner: root
    group: root
    content: |
      [Unit]
      Description=Airflow Celery Flower
      Wants=network.target airflow-db.service airflow-scheduler.service
      After=network.target airflow-db.service airflow-scheduler.service

      [Service]
      User=airflow
      Environment=AIRFLOW_HOME=/var/lib/airflow
      Type=simple
      ExecStart=/var/lib/venvs/airflow/bin/airflow celery flower
      Restart=on-failure
      RestartSec=5s
      PrivateTmp=true

      [Install]
      WantedBy=multi-user.target
  notify:
    - Reload daemon files
    - Restart celery flower
  become: true

- name: Restart celery flower after upgrade
  ansible.builtin.systemd:
    name: airflow-celery-flower
    state: restarted
    enabled: true
  become: true
  when: airflow_upgraded | default(false)

- name: Ensure celery flower is started and enabled
  ansible.builtin.systemd:
    name: airflow-celery-flower
    state: started
    enabled: true
  become: true
