---
- name: Restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: true

- name: Restart openvpn-monitor
  ansible.builtin.systemd:
    name: openvpn-monitor
    state: restarted
    enabled: true

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
    force: true
