---
- name: Configure airflow celery worker
  ansible.builtin.include_tasks:
    file: configure.yaml
    apply:
      tags:
        - airflow-worker-service
  when: OS != 'macOS'
  tags:
    - airflow-worker-service
