---
CELERY_WORKER_COUNT: 1
CELERY_WORKER_QUEUES: "default,workers,{{inventory_hostname}},{{OS|lower}}"
CELERY_WORKER_CPU_QUOTA: ''
CELERY_WORKER_CPU_WEIGHT: 100
CELERY_WORKER_IO_WEIGHT: 100
CELERY_WORKER_MEMORY_HIGH: infinity
CELERY_WORKER_MEMORY_MAX: infinity
CELERY_WORKER_MEMORY_SWAP_MAX: infinity
CELERY_WORKER_TASKS_MAX: infinity
CELERY_WORKER_OOM_SCORE_ADJUST: 0
CELERY_WORKER_MANAGED_OOM_MEMORY_PRESSURE: auto
CELERY_WORKER_MANAGED_OOM_MEMORY_PRESSURE_LIMIT: ''
CELERY_WORKER_MANAGED_OOM_SWAP: auto
CELERY_WORKER_SLICE: ''
