---
FORGEJO_VERSION: 15.0.7
FORGEJO_SHA256: cb75c2780d13a8a8b91390e42615354219aac58fd86a9d20baa40f5281c8e9a3
FORGEJO_APP_NAME: Forgejo
FORGEJO_DOMAIN: localhost
FORGEJO_HTTP_ADDR: 127.0.0.1
FORGEJO_HTTP_PORT: 3000
FORGEJO_ROOT_URL: "http://{{ FORGEJO_DOMAIN }}:{{ FORGEJO_HTTP_PORT }}/"
FORGEJO_SSH_ENABLED: false
FORGEJO_SSH_DOMAIN: "{{ FORGEJO_DOMAIN }}"
FORGEJO_SSH_PORT: 22
FORGEJO_SSH_USER: git
FORGEJO_START_SSH_SERVER: false
FORGEJO_SECRET_KEY: ''
FORGEJO_INTERNAL_TOKEN: ''
FORGEJO_LFS_JWT_SECRET: ''
FORGEJO_OAUTH2_JWT_SECRET: ''
FORGEJO_ADMIN_USERNAME: ''
FORGEJO_ADMIN_PASSWORD: ''
FORGEJO_ADMIN_EMAIL: ''
