---
CELERY_WORKER_INSTANCE_NAME: compute
CELERY_WORKER_INSTANCE_QUEUES: compute
CELERY_WORKER_INSTANCE_CONCURRENCY: 1
CELERY_WORKER_INSTANCE_SLICE: compute-batch.slice
CELERY_WORKER_INSTANCE_CPU_WEIGHT: 100
CELERY_WORKER_INSTANCE_IO_WEIGHT: 100
CELERY_WORKER_INSTANCE_OOM_SCORE_ADJUST: 500
CELERY_WORKER_INSTANCE_TASKS_MAX: 2048
