---
dependencies:
  - role: nginx

galaxy_info:
  role_name: nginx_routes
  author: 1kbgz
  description: Setup basic routes for nginx
  license: AGPL-3.0
  min_ansible_version: "2.12"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Ubuntu
  galaxy_tags:
    - development
