---
dependencies: []

galaxy_info:
  role_name: base
  author: 1kbgz
  description: Base System Dependencies
  license: AGPL-3.0
  min_ansible_version: "2.12"
  platforms:
    - name: EL
    - name: Raspbian
    - name: Ubuntu
    - name: macOS
  galaxy_tags:
    - development
