---
BACKUP_MONITOR_CHECKS: []
BACKUP_MONITOR_SMTP_HOST: ''
BACKUP_MONITOR_SMTP_PORT: 587
BACKUP_MONITOR_SMTP_USER: ''
BACKUP_MONITOR_SMTP_PASSWORD: ''
BACKUP_MONITOR_SMTP_FROM: ''
BACKUP_MONITOR_EMAIL_TO: ''
