---
- name: Setup /etc/hosts
  ansible.builtin.copy:
    dest: /etc/hosts
    content: |
      127.0.0.1 {{ inventory_hostname }}
  when: not inventory_hostname is match("ipa*")  # NOTE: freeipa can't have 127.0.0.1 mapping to host

# - name: Add mappings to /etc/hosts
#   ansible.builtin.blockinfile:
#     path: /etc/hosts
#     block: |
#       127.0.0.1 {{ inventory_hostname }}
#     marker: "# {mark} ANSIBLE MANAGED BLOCK - localhost"
#   when: not inventory_hostname is match("ipa*")  # NOTE: freeipa can't have 127.0.0.1 mapping to host

# - name: Add mappings to /etc/hosts
#   ansible.builtin.blockinfile:
#     path: /etc/hosts
#     block: |
#       {{ item.ip }} {{ item.name }}
#     marker: "# {mark} ANSIBLE MANAGED BLOCK - VPN - {{ item.name }}"
#   loop: "{{ VPN_HOSTS }}"
